version: "3"
services:
  phpfpm:
    build: ./phpfpm
    volumes:
      - ./phpfpm/src:/var/www/html
    environment:
      url: "${GET_URL}"
      auth: "${AUTH}"
      COMPOSER_ALLOW_SUPERUSER: 1

  web:
    build: ./web
    ports:
      - "${PORT}:80"
    depends_on:
      - phpfpm

  redis:
    image: redis:5-alpine